import { OnInit, EventEmitter, OnChanges, ElementRef } from '@angular/core';
import { FormControl } from '@angular/forms';
export declare class TagCommentComponent implements OnInit, OnChanges {
    infoDesc: FormControl;
    topDropdown: number;
    leftDropdown: number;
    topTooltip: number;
    leftTooltip: number;
    eleRef: ElementRef;
    statusTagOpen: boolean;
    infoActual: any;
    statusTagActive: boolean;
    statusSend: boolean;
    propertyTag: string;
    statusTooltip: boolean;
    statusReq: any;
    statusLoading: boolean;
    statusSendDel: boolean;
    statusFilled: boolean;
    actualInfoTag: any;
    stReqTag: boolean;
    tagProperty: string;
    reqTag: any;
    tagComp: ElementRef;
    onSendInfoTag: EventEmitter<any>;
    onDeleteInfoTag: EventEmitter<any>;
    constructor(eleRef: ElementRef);
    onResize(event: any): void;
    onScroll(event: any): void;
    onKeydown(evt: KeyboardEvent): void;
    ngOnInit(): void;
    ngOnChanges(): void;
    openRegisterTag(): void;
    chOpen(): void;
    openRegisterToggle(): void;
    closeRegisterTag(): void;
    openTooltip(): void;
    toggleTooltip(): void;
    closeTooltip(): void;
    closeTooltip2(): void;
    sendInfoTag(comment: string): void;
    deleteInfoTag(comment: string): void;
    msgError(firstError: any, secondError: any): string;
}
