import { ElementRef, EventEmitter } from '@angular/core';
import { OnChanges, OnInit } from '@angular/core';
export declare class MsdFilterSearchComponent implements OnInit, OnChanges {
    iconButton: string;
    titleButton: string;
    titleContButton: string;
    subTitle: string;
    listInfo: any;
    statusDefaultAll: boolean;
    arrSelectSimple: boolean;
    typeOrder: string;
    propertyRelevant: string;
    onClick: EventEmitter<string>;
    infoUlList: ElementRef;
    dropContent: ElementRef;
    toggleButton: ElementRef;
    drop: ElementRef;
    onGlobalMouseDown(event: any): void;
    onResize(event: any): void;
    onScroll(event: any): void;
    onKeydownHandler(evt: KeyboardEvent): void;
    onKeydown(evt: KeyboardEvent): void;
    statusOpen: boolean;
    infoList: any;
    top: number;
    left: number;
    eleRef: ElementRef;
    statusDefault: boolean;
    statusOpenSelect: boolean;
    simpleSelectArr: boolean;
    relevantProperty: string;
    orderType: string;
    actualItem: string;
    topUl: number;
    leftUl: number;
    widthUl: number;
    generalItem: any;
    constructor(eleRef: ElementRef);
    ngOnInit(): void;
    ngOnChanges(): void;
    orderNoRepeat(infoArray: any): unknown[] | undefined;
    setInfoFirstItem(): void;
    convertCamelCase(info: string): string | undefined;
    openSelect(): void;
    closeSelect(): void;
    openFilBtn(): void;
    closeFilBtn(): void;
    toggleFilBtn(): void;
    closeGeneral(): void;
    changeVal(): void;
    determinateDimentions(): void;
    changeOptionsSelect(...newItem: any[]): void;
    sendInfo(): void;
}
