import { ElementRef, EventEmitter, OnInit, Renderer2, OnChanges, AfterContentInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
export declare class NewKeycardInputComponent implements OnInit, OnChanges, AfterContentInit {
    private _render;
    private _fb;
    activatedBorderWarning: boolean;
    cardError: boolean;
    statusIn: string;
    iconMsg: string;
    statusActived: boolean;
    nameIconInputOne: string;
    nameIconInputTwo: string;
    keyCardOne: string;
    keyCardTwo: string;
    msgErrors: string[];
    titleKey: string;
    subtitleOne: string;
    subtitleTwo: string;
    noEqualKey: string;
    actualKey: string;
    finishPassKey: boolean;
    set status(value: string);
    c1New: ElementRef<HTMLInputElement>;
    c2New: ElementRef<HTMLInputElement>;
    c3New: ElementRef<HTMLInputElement>;
    c4New: ElementRef<HTMLInputElement>;
    c1Repeat: ElementRef<HTMLInputElement>;
    c2Repeat: ElementRef<HTMLInputElement>;
    c3Repeat: ElementRef<HTMLInputElement>;
    c4Repeat: ElementRef<HTMLInputElement>;
    changeKey: EventEmitter<string>;
    passCardOne: EventEmitter<string>;
    passCardTwo: EventEmitter<string>;
    formNewKey: FormGroup;
    formRepeatKey: FormGroup;
    constructor(_render: Renderer2, _fb: FormBuilder);
    ngOnInit(): void;
    ngAfterContentInit(): void;
    ngOnChanges(): void;
    changeIconPass(value: any): void;
    onlyNumber(event: any): boolean;
    moveToInput(event: any): void;
    backToInput(event: any): void;
    backPass(): void;
    sendValuesKeyOne(): void;
    sendValuesKeyTwo(): void;
    checkPassOne(): void;
    resetPassTwo(): void;
}
