import { ElementRef, EventEmitter, OnChanges, OnInit, Renderer2 } from '@angular/core';
import { FormGroup, FormBuilder } from '@angular/forms';
export declare class PassInputComponent implements OnInit, OnChanges {
    private _fb;
    private _render;
    statusIn: string;
    iconMsg: string;
    statusActived: boolean;
    private _keyOne;
    private _keyTwo;
    percentAvan: object;
    activatedBorderAlert: boolean;
    nameIconInputOne: string;
    nameIconInputTwo: string;
    activatedBorderWarning: boolean;
    msgAll: string[];
    titleHeader?: string;
    set msg(value: string[]);
    finishPass: boolean;
    set status(value: string);
    passOneIn: ElementRef<HTMLInputElement>;
    passTwoIn: ElementRef<HTMLInputElement>;
    passOne: EventEmitter<string>;
    passTwo: EventEmitter<string>;
    changePass: EventEmitter<string>;
    formPasswordOne: FormGroup;
    formPasswordTwo: FormGroup;
    constructor(_fb: FormBuilder, _render: Renderer2);
    ngOnInit(): void;
    ngOnChanges(): void;
    checkPassOne(): boolean;
    checkPassTwo(): void;
    onlyAlphaNumb(event: KeyboardEvent): boolean;
    changeIconPass(value: any): void;
    changeBarStatus(): void;
    resetPassOne(): void;
    resetPassTwo(): void;
    backPass(): void;
    closeIconEye(): void;
}
