import { OnInit, EventEmitter, OnChanges, ElementRef, Renderer2 } from '@angular/core';
import { FormControl } from '@angular/forms';
export declare class FavoriteStarComponent implements OnInit, OnChanges {
    private renderer;
    infoItem: any;
    idxInfo: number;
    sizeStar: number;
    statusInfoStar: any;
    numFavoriteActive: number;
    drop: ElementRef;
    dropContentStar: ElementRef;
    tooltipForm: ElementRef;
    tooltipDelete: ElementRef;
    inputForm: ElementRef;
    msgLastAdd: ElementRef;
    onClick: EventEmitter<any>;
    addNewItem: EventEmitter<any>;
    removeNewItem: EventEmitter<any>;
    statusS: boolean;
    infoIdx: number;
    itemInfo: any;
    starSize: number;
    eleRef: ElementRef;
    infoDesc: FormControl;
    topDropdown: string;
    leftDropdown: string | number;
    starInfoStatus: any;
    activeFavoriteNum: number;
    statusModalStarDel: boolean;
    constructor(eleRef: ElementRef, renderer: Renderer2);
    onKeyup(evt: KeyboardEvent): void;
    onKeydown(evt: KeyboardEvent): void;
    onResize(event: any): void;
    onScroll(event: any): void;
    ngOnInit(): void;
    ngOnChanges(): void;
    statusStarOpen(): void;
    statusStarOpenFcs(): void;
    clckCloseEvn(info: any): void;
    statusStarClose(): void;
    statusStarModalClose(): void;
    statusStarModalOpen(): void;
    addNewFavorites(e: any): void;
    removeNewFavorites(): void;
    dctNewElement(): void;
    rzResp(): boolean;
    getPosPopUpResp(): void;
}
