import { OnInit, EventEmitter, OnChanges, ElementRef, Renderer2 } from '@angular/core';
import { CheckboxItemService } from './checkbox-item.service';
export declare class CheckboxItemComponent implements OnInit, OnChanges {
    private render;
    private eleRef;
    checkboxService: CheckboxItemService;
    size: any;
    sizeScale: any;
    set infoItem(value: any);
    actualStatus: boolean;
    set countItems(value: any);
    set limitActive(value: number);
    statusCheck: EventEmitter<any>;
    checkItem: ElementRef;
    tooltipLimit: ElementRef;
    onResize(event: any): void;
    onScroll(event: any): void;
    onKeyUp(evt: KeyboardEvent): void;
    onClick(evt: KeyboardEvent): void;
    onMouseEnter(targetElement: any): void;
    actualSizeBlock: any;
    checkStatus: boolean;
    typeScale: any;
    activeLimit: number;
    topTooltip: string;
    leftTooltip: string;
    statusOpenTooltip: boolean;
    itemInfo: any;
    countInfo: any;
    off: any;
    on: any;
    constructor(render: Renderer2, eleRef: ElementRef, checkboxService: CheckboxItemService);
    ngOnInit(): void;
    ngOnChanges(): void;
    statusResp(): boolean;
    changeCheckStatus(e: Event): void;
    openTooltip(): void;
    closeTooltip(e: Event): void;
}
