import { OnInit, ElementRef, OnChanges, EventEmitter, Renderer2 } from '@angular/core';
export declare class SelectDinamicComponent implements OnInit, OnChanges {
    private eleRef;
    private _render;
    infoUlList: ElementRef;
    dropContent: ElementRef;
    infoDataSelect: Array<any>;
    arrSelectSimple: boolean;
    propertyRelevant: string;
    typeOrder: string;
    statusDefaultAll: boolean;
    statusDoubleCharge: boolean;
    set infoExt(value: any);
    onClick: EventEmitter<string>;
    onResize(event: any): void;
    onScroll(event: any): void;
    onKeydown(evt: KeyboardEvent): void;
    selectDataInfo: any;
    simpleSelectArr: boolean;
    relevantProperty: string;
    orderType: string;
    actualItem: string;
    statusOpen: boolean;
    allDefaultStatus: boolean;
    topUl: number;
    leftUl: number;
    widthUl: number;
    statusChange: boolean;
    infoX: any;
    constructor(eleRef: ElementRef, _render: Renderer2);
    ngOnInit(): void;
    ngOnChanges(): void;
    setInfoFirstItem(): void;
    convertCamelCase2(info: string): string;
    convertCamelCase(info: string): string;
    orderNoRepeat(infoArray: any): any;
    openToggle(): void;
    open(): void;
    close(): void;
    determinateDimentions(): void;
    verifyOptionAll(infoArr: any): any;
    changeOptionsSelect(...newItem: any[]): void;
}
